// Per-station aerial/photo backgrounds for the airport detail header, keyed by ICAO.
// Add an entry as each photo is supplied; the header uses it in place of the runway schematic.
window.PHOTOS = {
  KPVU: "photos/KPVU.jpg",
  KSFO: "photos/KSFO.jpg",
  KSAN: "photos/KSAN.jpg",
  KSNA: "photos/KSNA.jpg",
  KLAS: "photos/KLAS.jpg",
  KOGD: "photos/KOGD.jpg",
  KSBD: "photos/KSBD.jpg",
  KMSY: "photos/KMSY.jpg",
  KPHX: "photos/KPHX.jpg",
  KGPT: "photos/KGPT.jpg",
  KBFM: "photos/KBFM.jpg",
  KPNS: "photos/KPNS.jpg",
  KRSW: "photos/KRSW.jpg",
  KPBI: "photos/KPBI.jpg",
  KMCO: "photos/KMCO.jpg",
  KLAX: "photos/KLAX.jpg",
  KMSN: "photos/KMSN.jpg",
  KSPI: "photos/KSPI.jpg",
  KEVV: "photos/KEVV.jpg",
  KHSV: "photos/KHSV.jpg",
  KVRB: "photos/KVRB.jpg",
  KGSP: "photos/KGSP.jpg",
  KMYR: "photos/KMYR.jpg",
  KEWN: "photos/KEWN.jpg",
  KORF: "photos/KORF.jpg",
  KAVP: "photos/KAVP.jpg",
  KHPN: "photos/KHPN.jpg",
  KSWF: "photos/KSWF.jpg",
  KBDL: "photos/KBDL.jpg",
  KPVD: "photos/KPVD.jpg",
  KBTV: "photos/KBTV.jpg",
  KOGS: "photos/KOGS.jpg",
};
